language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8
before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.0-amd64.deb
  && sudo dpkg -i --force-confnew elasticsearch-7.7.0-amd64.deb
before_script:
- sleep 10
install:
- pip install pipenv
- pipenv install --dev --system
script: make test
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: GKXKVzgqOSadR0Er/XLJ/b+OmdA+3ymXeag4ubko78xWKWSuyiSSpNvjYjM1znOHppiLNl8svT3N+M0L8fKlff3yxJlnDgUeVA6KcOJa/D72eNzH1pQfbXon6l+e7laMwTV2+X8kFrONhdX8no0E2wih56gv6Ln+OMOBfeGtIne2hzlFmoCja8gOiMzagB5OyK5u8gEXRoTyTULQUsOmHvP1Q3rFp7IXTRjKfPZKvOIBZqvz33pg2r/DNtCk0VvssJBxyPZJfyAVqqnPOfV8siixs/qc/pLsKpYvaNOdfqtq0nDHHpK+FxtglK6D6CJKWWJTAfUr9qDOr/RjZrAGKMMYZ3cb4u0RS3Sy0t7N4ZJ7tr61mxDPEv0T/t/VTlivnHx5ZeY0XrxkeCpMyoj5NrUAEuTX1b/dfvqaCuXDoUV+b4c/HwcWKOw6TXWOxY+cH3RmPgEkePE/saDhj9V5+dPa+f298G/5rnOr0Nd9Pl6Ubj5rdtOSuk4PZkou9xIaoY6EUWm2ToBVmKzt1G2Ww9FRKgnGYhBNDslwe5RZcHx1hYzSijXIWzN0auRW0/CssvBOn1qbb0nLoShBd7JUgrw6N5+yaA7Yt8mq2ZTUtI5BOl0FSj7cfMSj+zu21crt/dwq7VIQp8Vb0P9ECdc4K8bBY9wDRWdBqpTnvB7A1CA=
