language: python
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.0-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.7.0-amd64.deb
before_script:
  - sleep 10
python:
  - "2.7"
services: elasticsearch
install:
  - "pip install --upgrade -r test.req"
script: make test
after_success:
  - coveralls
notifications:
  slack: catholabs:9yCjbY6Jgn3Xdy9hwq6PyLEJ
